# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('exercises', models.IntegerField(null=True)),
                ('laboratories', models.IntegerField(null=True)),
                ('project', models.IntegerField(null=True)),
                ('seminars', models.IntegerField(null=True)),
                ('exam', models.IntegerField(null=True)),
                ('ects', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
