# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrade',
            fields=[
                ('usergrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_final', models.BooleanField()),
                ('category', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('professor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='user.Profile')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user.Profile')),
            ],
        ),
    ]
