# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseId',
            new_name='course_id',
        ),
    ]
