# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20171114_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ects',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='exercises',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='laboratories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='project',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seminars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seminarss',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserRole'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
