# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171119_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seminarss',
        ),
        migrations.AddField(
            model_name='course',
            name='seminarsz',
            field=models.IntegerField(null=True),
        ),
    ]
