# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171122_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='app.UserRole'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together=set([('profile', 'course')]),
        ),
    ]
