# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171122_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.UserRole'),
        ),
    ]
