# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usergrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergrade',
            old_name='professor_user_id',
            new_name='professor_user',
        ),
        migrations.RenameField(
            model_name='usergrade',
            old_name='student_user_id',
            new_name='student_user',
        ),
        migrations.RenameField(
            model_name='usergrade',
            old_name='usergrade',
            new_name='usergrade_id',
        ),
    ]
