# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171205_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usergrade',
            name='professor_user',
        ),
        migrations.RemoveField(
            model_name='usergrade',
            name='student_user',
        ),
        migrations.DeleteModel(
            name='UserGrade',
        ),
    ]
